In [1]:
import numpy as np

In [2]:
a = np.array([1,2,3,4,5,9])
b = np.array([[1,2,3],[4,5,6]])
c = np.array([[[1,2,3],[4,5,6]],[[7,8,9],[10,11,12]]])

In [3]:
a.shape

(6,)

In [4]:
b.shape

(2, 3)

In [5]:
c.shape

(2, 2, 3)

In [6]:
c.size

12

In [7]:
b.size

6

In [8]:
c.reshape(3,2,2)

array([[[ 1,  2],
        [ 3,  4]],

       [[ 5,  6],
        [ 7,  8]],

       [[ 9, 10],
        [11, 12]]])

In [10]:
a = np.arange(1,10).reshape(3,3)
a

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [11]:
# 30,50 50,30 15,10   5,5,3,2
np.arange(1,151).reshape(5,5,2,3)

array([[[[  1,   2,   3],
         [  4,   5,   6]],

        [[  7,   8,   9],
         [ 10,  11,  12]],

        [[ 13,  14,  15],
         [ 16,  17,  18]],

        [[ 19,  20,  21],
         [ 22,  23,  24]],

        [[ 25,  26,  27],
         [ 28,  29,  30]]],


       [[[ 31,  32,  33],
         [ 34,  35,  36]],

        [[ 37,  38,  39],
         [ 40,  41,  42]],

        [[ 43,  44,  45],
         [ 46,  47,  48]],

        [[ 49,  50,  51],
         [ 52,  53,  54]],

        [[ 55,  56,  57],
         [ 58,  59,  60]]],


       [[[ 61,  62,  63],
         [ 64,  65,  66]],

        [[ 67,  68,  69],
         [ 70,  71,  72]],

        [[ 73,  74,  75],
         [ 76,  77,  78]],

        [[ 79,  80,  81],
         [ 82,  83,  84]],

        [[ 85,  86,  87],
         [ 88,  89,  90]]],


       [[[ 91,  92,  93],
         [ 94,  95,  96]],

        [[ 97,  98,  99],
         [100, 101, 102]],

        [[103, 104, 105],
         [106, 107, 108]],

        [[109, 110, 11

In [12]:
np.linspace(1,10,20)

array([ 1.        ,  1.47368421,  1.94736842,  2.42105263,  2.89473684,
        3.36842105,  3.84210526,  4.31578947,  4.78947368,  5.26315789,
        5.73684211,  6.21052632,  6.68421053,  7.15789474,  7.63157895,
        8.10526316,  8.57894737,  9.05263158,  9.52631579, 10.        ])

In [13]:
# Iteration of array 
l = [1,2,3,4,7]
l

[1, 2, 3, 4, 7]

In [14]:
a = np.array(l)
a

array([1, 2, 3, 4, 7])

In [15]:
for i in a:
    print(i)

1
2
3
4
7


In [16]:
b

array([[1, 2, 3],
       [4, 5, 6]])

In [17]:
for i in b:
    for j in i:
        print(j)

1
2
3
4
5
6


In [18]:
c

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

In [19]:
for i in c:
    for j in i:
        for k in j:
            print(k)

1
2
3
4
5
6
7
8
9
10
11
12


In [20]:
for i in np.nditer(c):
    print(i)

1
2
3
4
5
6
7
8
9
10
11
12


In [22]:
a = np.arange(1,10)
b = np.arange(21,30)
np.concatenate((a,b))

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 21, 22, 23, 24, 25, 26, 27, 28,
       29])

In [24]:
a = np.arange(10,20).reshape(2,5)
b = np.arange(150,160).reshape(2,5)
np.concatenate((a,b))

array([[ 10,  11,  12,  13,  14],
       [ 15,  16,  17,  18,  19],
       [150, 151, 152, 153, 154],
       [155, 156, 157, 158, 159]])

In [25]:
c.min()

1

In [26]:
c.max()

12

In [27]:
c.argmin()

0

In [28]:
c.argmax()

11

In [29]:
np.sum(a)

145

In [30]:
np.sum(a,1)

array([60, 85])

In [31]:
a

array([[10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

In [32]:
np.sum(a,0)

array([25, 27, 29, 31, 33])

In [35]:
np.argmin(c,0)

array([[0, 0, 0],
       [0, 0, 0]], dtype=int64)

In [36]:
np.argmax(c,1)

array([[1, 1, 1],
       [1, 1, 1]], dtype=int64)

In [37]:
np.hstack(c)

array([[ 1,  2,  3,  7,  8,  9],
       [ 4,  5,  6, 10, 11, 12]])

In [38]:
np.vstack(c)

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [40]:
b

array([[150, 151, 152, 153, 154],
       [155, 156, 157, 158, 159]])

In [41]:
np.hstack((a,b))

array([[ 10,  11,  12,  13,  14, 150, 151, 152, 153, 154],
       [ 15,  16,  17,  18,  19, 155, 156, 157, 158, 159]])

In [42]:
np.vstack((a,b))

array([[ 10,  11,  12,  13,  14],
       [ 15,  16,  17,  18,  19],
       [150, 151, 152, 153, 154],
       [155, 156, 157, 158, 159]])

In [43]:
np.r_[a,b]

array([[ 10,  11,  12,  13,  14],
       [ 15,  16,  17,  18,  19],
       [150, 151, 152, 153, 154],
       [155, 156, 157, 158, 159]])

In [44]:
np.c_[a,b]

array([[ 10,  11,  12,  13,  14, 150, 151, 152, 153, 154],
       [ 15,  16,  17,  18,  19, 155, 156, 157, 158, 159]])

In [46]:
np.column_stack((a,b)) # c_,hstack

array([[ 10,  11,  12,  13,  14, 150, 151, 152, 153, 154],
       [ 15,  16,  17,  18,  19, 155, 156, 157, 158, 159]])

In [47]:
np.row_stack((a,b)) # r_,vstack 

array([[ 10,  11,  12,  13,  14],
       [ 15,  16,  17,  18,  19],
       [150, 151, 152, 153, 154],
       [155, 156, 157, 158, 159]])

In [55]:
np.var(c)
np.std(c)
np.mean(c)
np.median(c)
np.average(c)

6.5

In [59]:
np.corrcoef(a)

array([[1., 1.],
       [1., 1.]])

In [61]:
np.cumsum(a)

array([ 10,  21,  33,  46,  60,  75,  91, 108, 126, 145], dtype=int32)

In [62]:
a

array([[10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

In [63]:
b

array([[150, 151, 152, 153, 154],
       [155, 156, 157, 158, 159]])

In [64]:
b.sort(axis = 0)

In [65]:
b

array([[150, 151, 152, 153, 154],
       [155, 156, 157, 158, 159]])

In [69]:
k = np.array([[1,45,6,8,9,23,43],[258,631,10869,28,17,21,92]])
k

array([[    1,    45,     6,     8,     9,    23,    43],
       [  258,   631, 10869,    28,    17,    21,    92]])

In [67]:
k.sort()

In [70]:
k

array([[    1,    45,     6,     8,     9,    23,    43],
       [  258,   631, 10869,    28,    17,    21,    92]])

In [72]:
k.sort(axis=1)
k

array([[    1,     6,     8,     9,    21,    43,    45],
       [   17,    23,    28,    92,   258,   631, 10869]])

In [73]:
np.sqrt(c)

array([[[1.        , 1.41421356, 1.73205081],
        [2.        , 2.23606798, 2.44948974]],

       [[2.64575131, 2.82842712, 3.        ],
        [3.16227766, 3.31662479, 3.46410162]]])

In [76]:
np.log(c)
np.log2(c)
np.log10(c)

array([[[0.        , 0.30103   , 0.47712125],
        [0.60205999, 0.69897   , 0.77815125]],

       [[0.84509804, 0.90308999, 0.95424251],
        [1.        , 1.04139269, 1.07918125]]])

In [80]:
np.sin(c)
np.cos(c)
np.tan(c)
np.exp(c)

array([[[2.71828183e+00, 7.38905610e+00, 2.00855369e+01],
        [5.45981500e+01, 1.48413159e+02, 4.03428793e+02]],

       [[1.09663316e+03, 2.98095799e+03, 8.10308393e+03],
        [2.20264658e+04, 5.98741417e+04, 1.62754791e+05]]])

In [85]:
np.remainder(c,2)
np.add(a,2)
np.subtract(a,1)
np.multiply(a,2)
np.divide(a,2)

array([[5. , 5.5, 6. , 6.5, 7. ],
       [7.5, 8. , 8.5, 9. , 9.5]])

In [87]:
np.degrees(c)

array([[[ 57.29577951, 114.59155903, 171.88733854],
        [229.18311805, 286.47889757, 343.77467708]],

       [[401.07045659, 458.3662361 , 515.66201562],
        [572.95779513, 630.25357464, 687.54935416]]])

In [88]:
np.diff(c)

array([[[1, 1],
        [1, 1]],

       [[1, 1],
        [1, 1]]])

In [91]:
np.power(a,3)
np.reciprocal(c,dtype = float)

array([[[1.        , 0.5       , 0.33333333],
        [0.25      , 0.2       , 0.16666667]],

       [[0.14285714, 0.125     , 0.11111111],
        [0.1       , 0.09090909, 0.08333333]]])

In [92]:
a = np.array([1+2j,3+9j,7+45j])
a

array([1. +2.j, 3. +9.j, 7.+45.j])

In [93]:
np.real(a)

array([1., 3., 7.])

In [94]:
np.imag(a)

array([ 2.,  9., 45.])

In [95]:
np.random.randn(5)

array([-0.47058747, -1.23617824, -0.30126602, -0.29384133, -1.32707725])

In [98]:
np.random.randint(100,134,6)

array([113, 118, 111, 102, 119, 132])

In [100]:
np.random.choice([1,45,69,34,21,17])

34

In [101]:
c

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

In [104]:
np.random.shuffle(c)

In [105]:
c

array([[[ 7,  8,  9],
        [10, 11, 12]],

       [[ 1,  2,  3],
        [ 4,  5,  6]]])

In [107]:
np.random.normal()

0.23341037283415506

In [109]:
np.random.binomial(10,p=[0.1],size=(4))

array([1, 3, 1, 2])

In [110]:
c

array([[[ 7,  8,  9],
        [10, 11, 12]],

       [[ 1,  2,  3],
        [ 4,  5,  6]]])

In [111]:
c.transpose()

array([[[ 7,  1],
        [10,  4]],

       [[ 8,  2],
        [11,  5]],

       [[ 9,  3],
        [12,  6]]])

In [114]:
b

array([[150, 151, 152, 153, 154],
       [155, 156, 157, 158, 159]])

In [115]:
b.T

array([[150, 155],
       [151, 156],
       [152, 157],
       [153, 158],
       [154, 159]])